// Reads SVG flags from flag-icons and generates flags-data.js with
// data: URIs for each FIFA code (and the language picker codes).
// Uses simplified band-only versions for flags whose coat-of-arms blows
// up the bundle (Spain: 82KB, Iran: 15KB, Saudi: 10KB).

import fs from 'node:fs';
import path from 'node:path';
import { Buffer } from 'node:buffer';
import { optimize } from 'svgo';

const FIFA_TO_ISO = {
  ALG: 'dz', ARG: 'ar', AUS: 'au', AUT: 'at', BEL: 'be',
  BIH: 'ba', BRA: 'br', CAN: 'ca', CIV: 'ci', COD: 'cd',
  COL: 'co', CPV: 'cv', CRO: 'hr', CUW: 'cw', CZE: 'cz',
  ECU: 'ec', EGY: 'eg', ENG: 'gb-eng', ESP: 'es', FRA: 'fr',
  GER: 'de', GHA: 'gh', HAI: 'ht', IRN: 'ir', IRQ: 'iq',
  JOR: 'jo', JPN: 'jp', KOR: 'kr', KSA: 'sa', MAR: 'ma',
  MEX: 'mx', NED: 'nl', NOR: 'no', NZL: 'nz', PAN: 'pa',
  PAR: 'py', POR: 'pt', QAT: 'qa', RSA: 'za', SCO: 'gb-sct',
  SEN: 'sn', SUI: 'ch', SWE: 'se', TUN: 'tn', TUR: 'tr',
  URU: 'uy', USA: 'us', UZB: 'uz',
  // Historical winners in MUSEUM_INFO (Italy is not a 2026 participant
  // but appears as a past champion).
  ITA: 'it',
};

const LANG_TO_ISO = { es: 'es', en: 'gb', fr: 'fr', it: 'it', pt: 'br' };

// Hand-rolled simplified SVGs for flags whose coat-of-arms is too
// heavy to inline. These are the recognized "civil" / band-only
// versions of the same flags.
const SIMPLIFIED = {
  es: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 4"><path fill="#AA151B" d="M0 0h6v4H0z"/><path fill="#F1BF00" d="M0 1h6v2H0z"/></svg>`,
  ir: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 4"><path fill="#fff" d="M0 0h6v4H0z"/><path fill="#239F40" d="M0 0h6v1.333H0z"/><path fill="#DA0000" d="M0 2.667h6V4H0z"/></svg>`,
  sa: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 6 4"><path fill="#006C35" d="M0 0h6v4H0z"/><text x="3" y="2.6" font-family="serif" font-weight="bold" font-size="1.2" fill="#fff" text-anchor="middle">KSA</text></svg>`,
};

const flagsDir = 'node_modules/flag-icons/flags/4x3';

const svgoConfig = {
  multipass: true,
  plugins: [
    'preset-default',
    'removeDimensions',
    'sortAttrs',
  ],
};

function readFlagSvg(iso) {
  if (SIMPLIFIED[iso]) return SIMPLIFIED[iso];
  const p = path.join(flagsDir, `${iso}.svg`);
  if (!fs.existsSync(p)) return null;
  return fs.readFileSync(p, 'utf8');
}

function toDataUri(iso) {
  const svg = readFlagSvg(iso);
  if (!svg) return null;
  const optimized = optimize(svg, svgoConfig).data;
  return 'data:image/svg+xml;base64,' + Buffer.from(optimized).toString('base64');
}

const flags = {};
for (const [fifa, iso] of Object.entries(FIFA_TO_ISO)) {
  const uri = toDataUri(iso);
  if (uri) flags[fifa] = uri;
  else console.warn(`! missing flag for ${fifa} (${iso})`);
}
for (const [lang, iso] of Object.entries(LANG_TO_ISO)) {
  const uri = toDataUri(iso);
  if (uri) flags[`__lang_${lang}`] = uri;
  else console.warn(`! missing lang flag for ${lang} (${iso})`);
}

fs.writeFileSync(
  'flags-data.js',
  `// Auto-generated by gen-flags.mjs — do not edit by hand.\nexport const FLAGS = ${JSON.stringify(flags)};\n`
);

const total = Object.keys(flags).length;
const size = fs.statSync('flags-data.js').size;
console.log(`✓ flags-data.js  ${total} flags, ${(size / 1024).toFixed(1)} KB`);
